import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=fileURLToPath(new URL('../',import.meta.url));
const core=readFileSync(path.join(root,'src/shelf.mjs'),'utf8').replace(/^export /gm,'');
const sample=JSON.parse(readFileSync(path.join(root,'examples/session-inventory.json'),'utf8'));
const template=readFileSync(path.join(root,'src/index.template.html'),'utf8');
const version=JSON.parse(readFileSync(path.join(root,'ipollowork.plugin.json'))).package.version;
const html=template.replaceAll('/* VERSION */',version).replace('/* SHELF_CORE */',()=>core).replace('/* SAMPLE_JSON */',()=>JSON.stringify(sample).replaceAll('<','\\u003c'));
if(html.includes('/* SHELF_CORE */')||html.includes('/* SAMPLE_JSON */'))throw new Error('Unexpanded build placeholder');
mkdirSync(path.join(root,'ui'),{recursive:true});writeFileSync(path.join(root,'ui/index.html'),html);
console.log('Built ui/index.html without external runtime dependencies.');
